const express = require('express')
const cors = require('cors')
const routerCustomer = require('./customer')
const routerProduct = require('./product')
const routerAdmin = require('./admin')

const app = express()
app.use(express.json())
app.use(cors())
app.use(express.static('uploads'))
app.use(express.static('uploads/books'))
app.use(express.static('uploads/categories'))
app.use(express.static('uploads/computers'))
app.use(express.static('uploads/customer_images'))
app.use(express.static('uploads/default'))
app.use(express.static('uploads/laptops'))
app.use(express.static('uploads/mens_fashion'))
app.use(express.static('uploads/mobile_accessories'))
app.use(express.static('uploads/smartphones'))
app.use(express.static('uploads/smart_watches'))
app.use(express.static('uploads/tablets'))
app.use(express.static('uploads/tvs'))
app.use(express.static('uploads/womens_fashion'))
app.use(routerCustomer)
app.use(routerProduct)
app.use(routerAdmin)

app.listen(4000, '0.0.0.0', () => {
    console.log("Server started at port 4000")
})